In [2]:
import numpy as np

In [36]:
def partial_pivot_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)
    
    for k in range(n):   
        for i in range(k,n): 
            if abs(augmented_matrix[i][k]) > abs(augmented_matrix[k][k]):  
                augmented_matrix[[k,i]] = augmented_matrix[[i,k]]
            else: 
                pass  
        print(augmented_matrix)
    
    for i in range(n):
            
        if augmented_matrix[i][i] == 0.0:
            return None #Results in division by 0

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(augmented_matrix)   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

In [37]:
a = np.array([[-7, 2, -3, 4, -12], [5, -1, 14, -1, 13], [1, 9, -7, 5, 31], [-12, 13, -8, -4, -32]], float)
n=4
partial_pivot_gauss(n,a)

[[-12.  13.  -8.  -4. -32.]
 [  5.  -1.  14.  -1.  13.]
 [  1.   9.  -7.   5.  31.]
 [ -7.   2.  -3.   4. -12.]]
[[-12.  13.  -8.  -4. -32.]
 [  1.   9.  -7.   5.  31.]
 [  5.  -1.  14.  -1.  13.]
 [ -7.   2.  -3.   4. -12.]]
[[-12.  13.  -8.  -4. -32.]
 [  1.   9.  -7.   5.  31.]
 [  5.  -1.  14.  -1.  13.]
 [ -7.   2.  -3.   4. -12.]]
[[-12.  13.  -8.  -4. -32.]
 [  1.   9.  -7.   5.  31.]
 [  5.  -1.  14.  -1.  13.]
 [ -7.   2.  -3.   4. -12.]]
[[-12.          13.          -8.          -4.         -32.        ]
 [  0.          10.08333333  -7.66666667   4.66666667  28.33333333]
 [  0.           4.41666667  10.66666667  -2.66666667  -0.33333333]
 [  0.          -5.58333333   1.66666667   6.33333333   6.66666667]]
[[-12.          13.          -8.          -4.         -32.        ]
 [  0.          10.08333333  -7.66666667   4.66666667  28.33333333]
 [  0.           0.          14.02479339  -4.7107438  -12.74380165]
 [  0.           0.          -2.5785124    8.91735537  22.3553719 ]]
[[

In [35]:
a = np.array([[-7, 2, -3, 4, -12], [5, -1, 14, -1, 13], [1, 9, -7, 5, 31], [-12, 13, -8, -4, -32]], float)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[ -7.   2.  -3.   4. -12.]
 [  5.  -1.  14.  -1.  13.]
 [  1.   9.  -7.   5.  31.]
 [-12.  13.  -8.  -4. -32.]]
[[  5.  -1.  14.  -1.  13.]
 [ -7.   2.  -3.   4. -12.]
 [  1.   9.  -7.   5.  31.]
 [-12.  13.  -8.  -4. -32.]]
