#### Gaussian Elimination with Total Pivoting

For each row we 

In [1]:
import numpy as np

In [2]:
def pivot_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)
    swapping_list = []
    
    for i in range(n):
        
        largest = 0
        row_of_largest = 0
        column_of_largest = 0
        for j in range (i, n):
            for k in range (n):
                if abs(largest) < abs(augmented_matrix[j][k]):
                    largest = augmented_matrix[j][k]
                    row_of_largest = j
                    column_of_largest = k
                    #print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
                    
        if(row_of_largest != i or column_of_largest != i):
            augmented_matrix[[row_of_largest, i]] = augmented_matrix[[i, row_of_largest]]
            swap = [column_of_largest, i]
            swapping_list.append(swap)
            augmented_matrix[:,[i, int(column_of_largest)]] = augmented_matrix[:,[int(column_of_largest),i]]
        
        for j in range(i,n): 
            if abs(augmented_matrix[j][i]) > abs(augmented_matrix[i][i]):  
                augmented_matrix[[i,j]] = augmented_matrix[[j,i]]
            else: 
                pass  
        print(f'Pivot Etapa {i} \n{augmented_matrix}')
            
        if augmented_matrix[i][i] == 0.0:
            return None #Results in division by 0

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(f'Operate Etapa {i} \n{augmented_matrix}')   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
    
    for i in reversed(range (len(swapping_list))):
        x[swapping_list[i][0]], x[swapping_list[i][1]] = x[swapping_list[i][1]], x[swapping_list[i][0]]
        print(x)
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

In [4]:
example = np.array([[-7, 2, -3, 4, -12], [5, -1, 14, -1, 13], [1, 9, -7, 13, 31], [-12, 13, -8, -4, -32]], float)

pivot_gauss(4, example)

Pivot Etapa 0 
[[ 14.  -1.   5.  -1.  13.]
 [ -3.   2.  -7.   4. -12.]
 [ -7.   9.   1.  13.  31.]
 [ -8.  13. -12.  -4. -32.]]
Operate Etapa 0 
[[ 14.          -1.           5.          -1.          13.        ]
 [  0.           1.78571429  -5.92857143   3.78571429  -9.21428571]
 [  0.           8.5          3.5         12.5         37.5       ]
 [  0.          12.42857143  -9.14285714  -4.57142857 -24.57142857]]
Pivot Etapa 1 
[[ 14.          -1.           5.          -1.          13.        ]
 [  0.          12.5          3.5          8.5         37.5       ]
 [  0.           3.78571429  -5.92857143   1.78571429  -9.21428571]
 [  0.          -4.57142857  -9.14285714  12.42857143 -24.57142857]]
Operate Etapa 1 
[[ 1.40000000e+01 -1.00000000e+00  5.00000000e+00 -1.00000000e+00
   1.30000000e+01]
 [ 0.00000000e+00  1.25000000e+01  3.50000000e+00  8.50000000e+00
   3.75000000e+01]
 [ 0.00000000e+00  4.44089210e-16 -6.98857143e+00 -7.88571429e-01
  -2.05714286e+01]
 [ 0.00000000e+00  0.0

In [40]:
def find_largest(matrix, n):
    largest = 0
    row_of_largest = None
    column_largest = None
    for i in range (n):
        for j in range (n):
            if abs(largest) < abs(matrix[i][j]):
                largest = matrix[i][j]
                row_of_largest = i
                column_of_largest = j
                print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
        
example = np.array([[-1111, 0, 7], [3, 2, 1], [11, 6, 1]], float)
find_largest(example, 3)

largest = -1111.0, column = 0, row = 0
largest = 211111111.0, column = 1, row = 1


In [65]:
def find_largest_and_swap(matrix, n):
    largest = 0
    row_of_largest = 0
    column_of_largest = 0
    for i in range (n):
        for j in range (n):
            if abs(largest) < abs(matrix[i][j]):
                largest = matrix[i][j]
                row_of_largest = i
                column_of_largest = j
                print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
    matrix[[row_of_largest, 0]] = matrix[[0, row_of_largest]]
    matrix[:,[0, int(column_of_largest)]] = matrix[:,[int(column_of_largest),0]]
    print(matrix)
    
example = np.array([[-1111, 0, 7, 3], [3, 211111111, 1, ], [11, 6, 111, 11]], float).reshape(3, 3) 
print(example)
find_largest_and_swap(example, 3)

[[-1.11100000e+03  0.00000000e+00  7.00000000e+00]
 [ 3.00000000e+00  2.11111111e+08  1.00000000e+00]
 [ 1.10000000e+01  6.00000000e+00  1.11110000e+04]]
largest = -1111.0, column = 0, row = 0
largest = 211111111.0, column = 1, row = 1
[[ 2.11111111e+08  3.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -1.11100000e+03  7.00000000e+00]
 [ 6.00000000e+00  1.10000000e+01  1.11110000e+04]]


In [158]:
def find_largest_and_swap_many_times(matrix, n):
    swapping_list = []
    
    for k in range (n):
        largest = 0
        row_of_largest = 0
        column_of_largest = 0
        for i in range (k, n):
            for j in range (n):
                if abs(largest) < abs(matrix[i][j]):
                    largest = matrix[i][j]
                    row_of_largest = i
                    column_of_largest = j
                    print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
        if(row_of_largest != k or column_of_largest != k):
            matrix[[row_of_largest, k]] = matrix[[k, row_of_largest]]
            swap = [column_of_largest, k]
            swapping_list.append(swap)
            matrix[:,[k, int(column_of_largest)]] = matrix[:,[int(column_of_largest),k]]
        
    print(matrix)
    print(swapping_list)
    
example = np.array([[1, 0, 0, 0,0], [0, 2, 0, 0,0], [0, 0, 3, 0,0], [0, 0, 0, 4,0]], float)
print(example)
find_largest_and_swap_many_times(example, 4)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
largest = 1.0, column = 0, row = 0
largest = 2.0, column = 1, row = 1
largest = 3.0, column = 2, row = 2
largest = 4.0, column = 3, row = 3
largest = 2.0, column = 1, row = 1
largest = 3.0, column = 2, row = 2
largest = 2.0, column = 2, row = 2
largest = 1.0, column = 3, row = 3
[[4. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[3, 0], [2, 1]]


In [136]:
thislist = [["apple", "hi"], ["banana", "on"], ["cherry", "tr"]]
print(thislist[1][1])

on
