# Lineal Splines

Must be continuous. Must be a linear polinomial based interpolation.

This has a single solution.

# Quadratic Spline

Uses fragments of parabolae in order to aproximate.

This has multiple solutions.

In [1]:
import numpy as np

In [2]:
def pivot_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)
    swapping_list = []
    
    for i in range(n):
        
        largest = 0
        row_of_largest = 0
        column_of_largest = 0
        for j in range (i, n):
            for k in range (n):
                if abs(largest) < abs(augmented_matrix[j][k]):
                    largest = augmented_matrix[j][k]
                    row_of_largest = j
                    column_of_largest = k
                    #print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
                    
        if(row_of_largest != i or column_of_largest != i):
            augmented_matrix[[row_of_largest, i]] = augmented_matrix[[i, row_of_largest]]
            swap = [column_of_largest, i]
            swapping_list.append(swap)
            augmented_matrix[:,[i, int(column_of_largest)]] = augmented_matrix[:,[int(column_of_largest),i]]
        
        for j in range(i,n): 
            if abs(augmented_matrix[j][i]) > abs(augmented_matrix[i][i]):  
                augmented_matrix[[i,j]] = augmented_matrix[[j,i]]
            else: 
                pass  
        print(f'Pivot Etapa {i} \n{augmented_matrix}')
            
        if augmented_matrix[i][i] == 0.0:
            return None #Results in division by 0

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(f'Operate Etapa {i} \n{augmented_matrix}')   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
    
    for i in reversed(range (len(swapping_list))):
        x[swapping_list[i][0]], x[swapping_list[i][1]] = x[swapping_list[i][1]], x[swapping_list[i][0]]
        print(x)
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

In [6]:
A = np.array([[0, -4, 5, 0], [4, -12, 9, 1], [-5, 24, -17, 2]], float)
pivot_gauss(3, A)

Pivot Etapa 0 
[[ 24.  -5. -17.   2.]
 [-12.   4.   9.   1.]
 [ -4.   0.   5.   0.]]
Operate Etapa 0 
[[ 24.          -5.         -17.           2.        ]
 [  0.           1.5          0.5          2.        ]
 [  0.          -0.83333333   2.16666667   0.33333333]]
Pivot Etapa 1 
[[ 24.         -17.          -5.           2.        ]
 [  0.           2.16666667  -0.83333333   0.33333333]
 [  0.           0.5          1.5          2.        ]]
Operate Etapa 1 
[[ 24.         -17.          -5.           2.        ]
 [  0.           2.16666667  -0.83333333   0.33333333]
 [  0.           0.           1.69230769   1.92307692]]
Pivot Etapa 2 
[[ 24.         -17.          -5.           2.        ]
 [  0.           2.16666667  -0.83333333   0.33333333]
 [  0.           0.           1.69230769   1.92307692]]
Operate Etapa 2 
[[ 24.         -17.          -5.           2.        ]
 [  0.           2.16666667  -0.83333333   0.33333333]
 [  0.           0.           1.69230769   1.92307692]]
[0.7

In [8]:
A = np.array([[1.133, 0, 5.113, 5, 0], [-1.667, 8.4, 13.533, 7.8, 1], [0.533, -4.8, 12.867, -9.8, 2],[1,1,1,1,1]], float)
pivot_gauss(4, A)

Pivot Etapa 0 
[[13.533  8.4   -1.667  7.8    1.   ]
 [ 5.113  0.     1.133  5.     0.   ]
 [12.867 -4.8    0.533 -9.8    2.   ]
 [ 1.     1.     1.     1.     1.   ]]
Operate Etapa 0 
[[ 13.533        8.4         -1.667        7.8          1.        ]
 [  0.          -3.17366438   1.76282125   2.05302594  -0.37781719]
 [  0.         -12.78661051   2.11796187 -17.21613833   1.04921303]
 [  0.           0.37929506   1.12318037   0.42363112   0.92610655]]
Pivot Etapa 1 
[[ 13.533        7.8         -1.667        8.4          1.        ]
 [  0.         -17.21613833   2.11796187 -12.78661051   1.04921303]
 [  0.           2.05302594   1.76282125  -3.17366438  -0.37781719]
 [  0.           0.42363112   1.12318037   0.37929506   0.92610655]]
Operate Etapa 1 
[[ 13.533        7.8         -1.667        8.4          1.        ]
 [  0.         -17.21613833   2.11796187 -12.78661051   1.04921303]
 [  0.           0.           2.01538838  -4.69846875  -0.25269845]
 [  0.           0.           1.1