# Taller Práctico Matrices

## Punto 1

Considere el siguiente sistema de ecuaciones y resuelvalo mediante los métodos de Eliminación Gaussiana Simple, Eliminación Gaussiana con Pivote Parcial, y Eliminación Gaussiana con Pivoteo Totall.

**Sistema de ecuaciones 1**

$ -x_1 + 4x_4 - x_5 = 61 $

$ -x_2 - x_4 + 4x_5 - x6 = 14 $

$ 4x_1 - x_2 - x_4 = 8 $

$ -x_1 + 5x_2 - x_3 - x_5 = 5 $

$ x_2 + 5x_3 - x_6 = 9 $

$ -x_3 - x_5 + 6x_6 = 23 $

**Sistema de ecuaciones 2**

$ 2x_1 - x_2 + x_3 = -1 $

$ 3x_1 + 3x_2 + 7x_3 = 0 $

$ 3x_1 + 3x_2 + 5x_3 = 4 $

**Sistema de ecuaciones 3**

$ 10x_1 - 6x_2 + 37x_3 + 4x_4 = -15 $

$ 8x_1 - 3x_2 + 2x_3 + 34x_4 = 21 $

$ 5x_1+ 31x_2 - 2x_3 + 6x_4 = 5 $

$ 56x_1 + 6x_2 0 2x_3 - 5x_4 = -15 $

In [1]:
import numpy as np

# Eliminación Gaussiana Simple

In [7]:
def simple_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)
    
    for i in range(n):
        
        print(f'Etapa {i}')
        
        if augmented_matrix[i][i] == 0.0:
            augmented_matrix[[i, i + 1]] = augmented_matrix[[i + 1,i]]

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(augmented_matrix)   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]
    
    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

# Eliminación Gaussiana con Pivoteo Parical

In [8]:
#Así lo hace Samir
def partial_pivot_in_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)

    
    for i in range(n):
        
        for j in range(i,n): 
            if abs(augmented_matrix[j][i]) > abs(augmented_matrix[i][i]):  
                augmented_matrix[[i,j]] = augmented_matrix[[j,i]]
            else: 
                pass  
        print(f'Pivot Etapa {i} \n{augmented_matrix}')
            
        if augmented_matrix[i][i] == 0.0:
            return None #Results in division by 0

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(f'Operate Etapa {i} \n{augmented_matrix}')   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

# Eliminación Gaussiana con Pivoteo Total

In [9]:
def pivot_gauss(n, augmented_matrix):
    # Applying Gauss Elimination
    x = np.zeros(n)
    swapping_list = []
    
    for i in range(n):
        
        largest = 0
        row_of_largest = 0
        column_of_largest = 0
        for j in range (i, n):
            for k in range (n):
                if abs(largest) < abs(augmented_matrix[j][k]):
                    largest = augmented_matrix[j][k]
                    row_of_largest = j
                    column_of_largest = k
                    #print (f'largest = {largest}, column = {column_of_largest}, row = {row_of_largest}')
                    
        if(row_of_largest != i or column_of_largest != i):
            augmented_matrix[[row_of_largest, i]] = augmented_matrix[[i, row_of_largest]]
            swap = [column_of_largest, i]
            swapping_list.append(swap)
            augmented_matrix[:,[i, int(column_of_largest)]] = augmented_matrix[:,[int(column_of_largest),i]]
        
        for j in range(i,n): 
            if abs(augmented_matrix[j][i]) > abs(augmented_matrix[i][i]):  
                augmented_matrix[[i,j]] = augmented_matrix[[j,i]]
            else: 
                pass  
        print(f'Pivot Etapa {i} \n{augmented_matrix}')
            
        if augmented_matrix[i][i] == 0.0:
            return None #Results in division by 0

        for j in range(i+1, n):
            ratio = augmented_matrix[j][i]/augmented_matrix[i][i]
            
            #print(augmented_matrix)
            
            for k in range(n+1):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]
                
        print(f'Operate Etapa {i} \n{augmented_matrix}')   
                
    # Back Substitution
    x[n-1] = augmented_matrix[n-1][n]/augmented_matrix[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = augmented_matrix[i][n]

        for j in range(i+1,n):
            x[i] = x[i] - augmented_matrix[i][j]*x[j]

        x[i] = x[i]/augmented_matrix[i][i]
    
    for i in reversed(range (len(swapping_list))):
        x[swapping_list[i][0]], x[swapping_list[i][1]] = x[swapping_list[i][1]], x[swapping_list[i][0]]
        print(x)
        
    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %f' %(i,x[i]), end = '\t')

# Sistema de Ecuaciones 1

In [13]:
# Hacer la matriz

sistema_1 = np.array([[-1, 0, 0, 4, -1, 0, 61], [0, -1, 0, -1, 4, -1, 14], [4, -1, 0, -1, 0, 0, 8], [-1, 5, -1, 0, -1, 0, 5], [0, -1, 5, 0, 0, -1, 9], [0, 0, -1, 0, -1, 6, 23]], float)

print(sistema_1)

[[-1.  0.  0.  4. -1.  0. 61.]
 [ 0. -1.  0. -1.  4. -1. 14.]
 [ 4. -1.  0. -1.  0.  0.  8.]
 [-1.  5. -1.  0. -1.  0.  5.]
 [ 0. -1.  5.  0.  0. -1.  9.]
 [ 0.  0. -1.  0. -1.  6. 23.]]


In [11]:
# Eliminación Gaussiana Simple

simple_gauss(6, sistema_1)

Etapa 0
[[ -1.   0.   0.   4.  -1.   0.  61.]
 [  0.  -1.   0.  -1.   4.  -1.  14.]
 [  0.  -1.   0.  15.  -4.   0. 252.]
 [  0.   5.  -1.  -4.   0.   0. -56.]
 [  0.  -1.   5.   0.   0.  -1.   9.]
 [  0.   0.  -1.   0.  -1.   6.  23.]]
Etapa 1
[[ -1.   0.   0.   4.  -1.   0.  61.]
 [  0.  -1.   0.  -1.   4.  -1.  14.]
 [  0.   0.   0.  16.  -8.   1. 238.]
 [  0.   0.  -1.  -9.  20.  -5.  14.]
 [  0.   0.   5.   1.  -4.   0.  -5.]
 [  0.   0.  -1.   0.  -1.   6.  23.]]
Etapa 2
[[ -1.   0.   0.   4.  -1.   0.  61.]
 [  0.  -1.   0.  -1.   4.  -1.  14.]
 [  0.   0.  -1.  -9.  20.  -5.  14.]
 [  0.   0.   0.  16.  -8.   1. 238.]
 [  0.   0.   0. -44.  96. -25.  65.]
 [  0.   0.   0.   9. -21.  11.   9.]]
Etapa 3
[[  -1.        0.        0.        4.       -1.        0.       61.    ]
 [   0.       -1.        0.       -1.        4.       -1.       14.    ]
 [   0.        0.       -1.       -9.       20.       -5.       14.    ]
 [   0.        0.        0.       16.       -8.        1.     

In [14]:
# Eliminación Gaussiana con Pivoteo Parcial

partial_pivot_in_gauss(6, sistema_1)

Pivot Etapa 0 
[[ 4. -1.  0. -1.  0.  0.  8.]
 [ 0. -1.  0. -1.  4. -1. 14.]
 [-1.  0.  0.  4. -1.  0. 61.]
 [-1.  5. -1.  0. -1.  0.  5.]
 [ 0. -1.  5.  0.  0. -1.  9.]
 [ 0.  0. -1.  0. -1.  6. 23.]]
Operate Etapa 0 
[[ 4.   -1.    0.   -1.    0.    0.    8.  ]
 [ 0.   -1.    0.   -1.    4.   -1.   14.  ]
 [ 0.   -0.25  0.    3.75 -1.    0.   63.  ]
 [ 0.    4.75 -1.   -0.25 -1.    0.    7.  ]
 [ 0.   -1.    5.    0.    0.   -1.    9.  ]
 [ 0.    0.   -1.    0.   -1.    6.   23.  ]]
Pivot Etapa 1 
[[ 4.   -1.    0.   -1.    0.    0.    8.  ]
 [ 0.    4.75 -1.   -0.25 -1.    0.    7.  ]
 [ 0.   -0.25  0.    3.75 -1.    0.   63.  ]
 [ 0.   -1.    0.   -1.    4.   -1.   14.  ]
 [ 0.   -1.    5.    0.    0.   -1.    9.  ]
 [ 0.    0.   -1.    0.   -1.    6.   23.  ]]
Operate Etapa 1 
[[ 4.00000000e+00 -1.00000000e+00  0.00000000e+00 -1.00000000e+00
   0.00000000e+00  0.00000000e+00  8.00000000e+00]
 [ 0.00000000e+00  4.75000000e+00 -1.00000000e+00 -2.50000000e-01
  -1.00000000e+00  0.000

In [16]:
# Eliminación Gaussiana con Pivoteo Total

pivot_gauss(6, sistema_1)

Pivot Etapa 0 
[[ 5.47635135e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  3.55540541e+01]
 [ 0.00000000e+00  4.75000000e+00 -1.00000000e+00 -2.50000000e-01
  -1.00000000e+00  0.00000000e+00  7.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  4.78947368e+00 -5.26315789e-02
  -2.10526316e-01  0.00000000e+00  1.04736842e+01]
 [-1.09890110e-02  0.00000000e+00  0.00000000e+00  3.73626374e+00
  -1.05494505e+00  0.00000000e+00  6.34835165e+01]
 [-1.04705882e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.48235294e+00  0.00000000e+00  3.38588235e+01]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00 -1.00000000e+00
   0.00000000e+00  4.00000000e+00  8.00000000e+00]]
Operate Etapa 0 
[[ 5.47635135e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  3.55540541e+01]
 [ 0.00000000e+00  4.75000000e+00 -1.00000000e+00 -2.50000000e-01
  -1.00000000e+00  0.00000000e+00  7.00000000e+00]
 [ 0.00000000e+00  0.00000000e+

# Sistema de Ecuaciones 2

In [20]:
# Hacer la matriz

sistema_2 = np.array([[2, -1, 1, -1], [3, 3, 7, 0], [3, 3, 5, 4]], float)
A_2 = np.array([[2, -1, 1], [3, 3, 7], [3, 3, 5]], float)
b_2 = np.array([-1, 0, 4], float)

np.linalg.solve(A_2, b_2)

array([ 1.88888889,  2.77777778, -2.        ])

In [21]:
# Eliminación Gaussiana Simple

simple_gauss(3, sistema_2)

Etapa 0
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   4.5  3.5  5.5]]
Etapa 1
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Etapa 2
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]

Required solution is: 
X0 = 1.888889	X1 = 2.777778	X2 = -2.000000	

In [22]:
# Eliminación Gaussiana con Pivoteo Parcial

partial_pivot_in_gauss(3, sistema_2)

Pivot Etapa 0 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Operate Etapa 0 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Pivot Etapa 1 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Operate Etapa 1 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Pivot Etapa 2 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]
Operate Etapa 2 
[[ 2.  -1.   1.  -1. ]
 [ 0.   4.5  5.5  1.5]
 [ 0.   0.  -2.   4. ]]

Required solution is: 
X0 = 1.888889	X1 = 2.777778	X2 = -2.000000	

In [23]:
# Eliminación Gaussiana con Pivoteo Total

pivot_gauss(3, sistema_2)

Pivot Etapa 0 
[[ 5.5  4.5  0.   1.5]
 [ 1.  -1.   2.  -1. ]
 [-2.   0.   0.   4. ]]
Operate Etapa 0 
[[ 5.5         4.5         0.          1.5       ]
 [ 0.         -1.81818182  2.         -1.27272727]
 [ 0.          1.63636364  0.          4.54545455]]
Pivot Etapa 1 
[[ 5.5         0.          4.5         1.5       ]
 [ 0.          2.         -1.81818182 -1.27272727]
 [ 0.          0.          1.63636364  4.54545455]]
Operate Etapa 1 
[[ 5.5         0.          4.5         1.5       ]
 [ 0.          2.         -1.81818182 -1.27272727]
 [ 0.          0.          1.63636364  4.54545455]]
Pivot Etapa 2 
[[ 5.5         0.          4.5         1.5       ]
 [ 0.          2.         -1.81818182 -1.27272727]
 [ 0.          0.          1.63636364  4.54545455]]
Operate Etapa 2 
[[ 5.5         0.          4.5         1.5       ]
 [ 0.          2.         -1.81818182 -1.27272727]
 [ 0.          0.          1.63636364  4.54545455]]
[-2.          2.77777778  1.88888889]
[ 1.88888889  2.77777778 -

# Sistema de Ecuaciones 3 

In [24]:
# Hacer la matriz

sistema_3 = np.array([[10, -6, 37, 4, -15], [8, -3, 2, 34, 21], [5, 31, -2, 6, 5], [56, 6, -2, -5, -15]], float)
A_3 = np.array([[10, -6, 37, 4], [8, -3, 2, 34], [5, 31, -2, 6], [56, 6, -2, -5]], float)
b_3 = np.array([-15, 21, 5, -15], float)

np.linalg.solve(A_3, b_3)

array([-0.22416333,  0.03562348, -0.41449439,  0.69791664])

In [25]:
# Eliminación Gaussiana Simple

simple_gauss(4, sistema_3)

Etapa 0
[[  10.    -6.    37.     4.   -15. ]
 [   0.     1.8  -27.6   30.8   33. ]
 [   0.    34.   -20.5    4.    12.5]
 [   0.    39.6 -209.2  -27.4   69. ]]
Etapa 1
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.            0.          398.         -705.         -657.        ]]
Etapa 2
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.            0.            0.         -245.854132   -171.58569052]]
Etapa 3
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.   

In [26]:
# Eliminación Gaussiana con Pivoteo Parcial

partial_pivot_in_gauss(4, sistema_3)

Pivot Etapa 0 
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.            0.            0.         -245.854132   -171.58569052]]
Operate Etapa 0 
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.            0.            0.         -245.854132   -171.58569052]]
Pivot Etapa 1 
[[  10.           -6.           37.            4.          -15.        ]
 [   0.            1.8         -27.6          30.8          33.        ]
 [   0.            0.          500.83333333 -577.77777778 -610.83333333]
 [   0.            0.            0.         -245.854132   -171.58569052]]
Operate Etapa 1 
[[  10.           -6.           37.            4.        

In [27]:
# Eliminación Gaussiana con Pivoteo Total

pivot_gauss(4, sistema_3)

Pivot Etapa 0 
[[-577.77777778    0.          500.83333333    0.         -610.83333333]
 [  30.8           1.8         -27.6           0.           33.        ]
 [   4.           -6.           37.           10.          -15.        ]
 [-245.854132      0.            0.            0.         -171.58569052]]
Operate Etapa 0 
[[-5.77777778e+02  0.00000000e+00  5.00833333e+02  0.00000000e+00
  -6.10833333e+02]
 [ 0.00000000e+00  1.80000000e+00 -9.01730769e-01  0.00000000e+00
   4.37884615e-01]
 [ 0.00000000e+00 -6.00000000e+00  4.04673077e+01  1.00000000e+01
  -1.92288462e+01]
 [-2.84217094e-14  0.00000000e+00 -2.13112981e+02  0.00000000e+00
   8.83341346e+01]]
Pivot Etapa 1 
[[-5.77777778e+02  5.00833333e+02  0.00000000e+00  0.00000000e+00
  -6.10833333e+02]
 [-2.84217094e-14 -2.13112981e+02  0.00000000e+00  0.00000000e+00
   8.83341346e+01]
 [ 0.00000000e+00  4.04673077e+01 -6.00000000e+00  1.00000000e+01
  -1.92288462e+01]
 [ 0.00000000e+00 -9.01730769e-01  1.80000000e+00  0.00000000e+0

## Punto 6

Considere el siguiente sistema de ecuaciones. Resuelvalo de la forma más eficiente y justifique su elección. Calcule el determinante de la matriz A asociada al sistema de ecuaciones anteriores de la forma $ Ax = B $ sin calcular A y en el menor número de operaciones. Justifique su respuesta.

$\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 2 & 0 & 0 & 0\\
0 & 2 & 3 & 0 & 0\\
0 & 0 & 1 & 4 & 0\\
-3 & 0 & 0 & -1 & 5
\end{pmatrix}$
$\begin{pmatrix}
3 & 12 & 0 & 0 & 0\\
0 & -5 & 0 & 0 & 0\\
0 & 0 & 4 & 8 & 0\\
0 & 0 & 0 & 4 & 1\\
0 & 0 & 0 & 0 & 2
\end{pmatrix}$
$\begin{pmatrix}
x_1\\
x_2\\
x_3\\
x_4\\
x_5
\end{pmatrix}$
$ = $
$\begin{pmatrix}
20\\
8\\
-7\\
4\\
12
\end{pmatrix}$

In [32]:
matrix_1 = np.array([[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 2, 3, 0, 0], [0, 0, 1, 4, 0], [-3, 0, 0, -1, 5]], float)
matrix_2 = np.array([[3, 12, 0, 0, 0], [0, -5, 0, 0, 0], [0, 0, 4, 8, 0], [0, 0, 0, 4, 1], [0, 0, 0, 0, 2]], float)

final_matrix = matrix_1.dot(matrix_2)
final_matrix

array([[  3.,  12.,   0.,   0.,   0.],
       [  0., -10.,   0.,   0.,   0.],
       [  0., -10.,  12.,  24.,   0.],
       [  0.,   0.,   4.,  24.,   4.],
       [ -9., -36.,   0.,  -4.,   9.]])

In [37]:
b = np.array([[20], [8], [-7], [4], [12]], float)

augmented_matrix = np.append(final_matrix, b, axis=1)
augmented_matrix

array([[  3.,  12.,   0.,   0.,   0.,  20.],
       [  0., -10.,   0.,   0.,   0.,   8.],
       [  0., -10.,  12.,  24.,   0.,  -7.],
       [  0.,   0.,   4.,  24.,   4.,   4.],
       [ -9., -36.,   0.,  -4.,   9.,  12.]])

In [38]:
np.linalg.solve(final_matrix, b)

array([[ 9.86666667],
       [-0.8       ],
       [ 1.3375    ],
       [-1.29375   ],
       [ 7.425     ]])

In [40]:
simple_gauss(5, augmented_matrix)

# Elegí gausiana simple ya que es la que hace el menor número de operaciones, y dado que ningun método es iterativo, el más eficiente será el que haga menos operaciones.

Etapa 0
[[  3.    12.     0.     0.     0.    20.  ]
 [  0.   -10.     0.     0.     0.     8.  ]
 [  0.     0.    12.    24.     0.   -15.  ]
 [  0.     0.     0.    16.     4.     9.  ]
 [  0.     0.     0.     0.    10.    74.25]]
Etapa 1
[[  3.    12.     0.     0.     0.    20.  ]
 [  0.   -10.     0.     0.     0.     8.  ]
 [  0.     0.    12.    24.     0.   -15.  ]
 [  0.     0.     0.    16.     4.     9.  ]
 [  0.     0.     0.     0.    10.    74.25]]
Etapa 2
[[  3.    12.     0.     0.     0.    20.  ]
 [  0.   -10.     0.     0.     0.     8.  ]
 [  0.     0.    12.    24.     0.   -15.  ]
 [  0.     0.     0.    16.     4.     9.  ]
 [  0.     0.     0.     0.    10.    74.25]]
Etapa 3
[[  3.    12.     0.     0.     0.    20.  ]
 [  0.   -10.     0.     0.     0.     8.  ]
 [  0.     0.    12.    24.     0.   -15.  ]
 [  0.     0.     0.    16.     4.     9.  ]
 [  0.     0.     0.     0.    10.    74.25]]
Etapa 4
[[  3.    12.     0.     0.     0.    20.  ]
 [  0.   -1

# Taller Teórico Matrices 

## Punto 1

_Selección múltiple con una única respuesta._ El error característico en el método de Eliminación Gaussiana Simple es:

1. Error de truncamiento
2. Error de propagación <--
3. Error relativo
4. Error inherente
5. División por cero
    
## Punto 2

_Selección múltiple con una única respuesta._ La sustitución regresiva de fundamenta teoricamente en:

1. El intercambio de ecuaciones en un sistema de ecuaciones lineales produce un sistema de ecuaciones equivalente.
2. Realizar operaciones aritméticas a ambos lados de una igualdad con un mismo número. <--
3. Sustitución de términos que son iguales. <--
4. Sumar dos ecuaciones y sustituir una de ellas por el resultado de la suma.
    
## Punto 3

_Análisis de relación._ Sea un sistema de ecuaciones Ax=B, tal que A es triangular inferior. La solución más adecuada es por sustitución regresiva PORQUE al efectuar la sustitución regresiva a un sistema triangular, se realizan menos operaciones que en una Eliminación Gaussia.

La afirmación es falsa, lo más efectivo sería usar sustitución progresiva. La razón es falsa, ya que tora vez debe ser triangular superior.
    
## Punto 4

_Análisis de relación._ Suponga el pivoteo parcial o total. Las estrategias de pivoteo se utilizan para eliminar los efectos de la propagación de errores PORQUE Las estrategias de pivoteobuscan siempre que el valor de multiplicador en valor absoluto sea el menor posible y que sea siempre menor o igual que uno (1).

La afirmación y la razón son verdadera, y la razon justifica la afirmación.

## Punto 5

_Selección múltiple con múltiple respuesta._ El pivoteo parcial en la Eliminación Gaussiana se fundamenta teóricamente en que se produce un sistema de ecuaciones equivalente cuando:

1. Hay intercambio de ecuaciones. <--
2. Multiplicamos a ambos lados de una igualdad por un mismo número. 
3. Sumar dos ecuaciones y agregar el resultado de la suma al conjunto de ecuaciones. <--
4. Restar a ambos lados de la igualdad un mismo número. 